name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Set up environment
      run: npm i -g yarn gulp-cli
    - name: Build admin cms
      run: |
        cd projects/admin-cms
        yarn
        yarn prod
        
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Heroku
        uses: actions/heroku@1.0.0
