name: Deploy Backend API

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Set up environment
      run: npm install -g firebase-tools
    - name: Build admin cms
      run: |
        cd projects/backend-api/functions/src
        yarn
        yarn deploy
