name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: npm install, build
      run: |
        npm install --global @gridsome/cli
        cd projects/koogio-website
        npm install
        npm run build    
    - name: ZEIT Now Deployment
      uses: amondnet/now-deployment@v1
      with:
        zeit-token: ${{ secrets.ZEIT_TOKENN }}
        github-token: ${{ secrets.GITHUB_TOKE }}
        now-args: './dist --name koogio --prod --public'
