name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: npm install, build
      run: |
        npm install --global @gridsome/cli
        cd projects/koogio-website
        npm install
    - name: ZEIT Now Deployment
      uses: amondnet/now-deployment@v1
      with:
        zeit-token: ${{ secrets.ZEIT_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        now-args: '--name koogio --prod --public'
